apiVersion: v1
kind: Service
metadata:
  name: servicbackend
spec:
  selector:
    name: backend
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31496
    protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      hostNetwork: true
      containers:
      - name: backend
        image: mohamaddiwany/backend
        ports:
        - containerPort: 5000
      hostname: backend
