apiVersion: v1
kind: Service
metadata:
  name: servicfrontend
spec:
  selector:
    name: frontend
  type: NodePort
  ports:
  - port: 8000
    targetPort: 5000
    nodePort: 31495
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: mohamaddiwany/frontend
        ports:
        - containerPort: 5000
      hostname: frontend
